# Autogenerated by fastlane
#
# Ensure this file is checked in to source control!

source "https://rubygems.org"

gem 'cocoapods'
gem 'danger'
gem 'danger-conflict_checker'
gem 'danger-swiftlint'
gem 'danger-xcode_summary'
gem 'danger-xcodebuild'
gem 'fastlane'
gem 'golden_rose'
gem 'jazzy'
gem 'simctl'
gem 'xcpretty-json-formatter'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval(File.read(plugins_path), binding) if File.exist?(plugins_path)
