// swiftlint:disable:next type_body_length
public enum HardwareKeyboard: String, LaunchArgumentValue {
	case Arabic = "ar@hw=Arabic"
	case BulgarianBulgaria = "bg_BG@hw=Bulgarian - Phonetic"
	case Bengali = "bn@hw=Bangla"
	case Tibetan = "bo@hw=Tibetan-QWERTY"
	case CatalanSpain = "ca_ES@hw=Spanish - ISO"
	case Cherokee = "chr@hw=Cherokee-Nation"
	case CzechCzechRepublic = "cs_CZ@hw=Czech"
	case WelshUnitedKingdom = "cy_GB@hw=British"
	case DanishDenmark = "da_DK@hw=Danish"
	case GermanAustria = "de_AT@hw=German"
	case GermanGermany = "de_DE@hw=German"
	case GermanSwitzerland = "de_CH@hw=Swiss German"
	case GreekGreece = "el_GR@hw=Greek"
	case EnglishCanada = "en_CA@hw=Canadian"
	case EnglishAustralia = "en_AU@hw=Australian"
	case EnglishSingapore = "en_SG@hw=US"
	case EnglishUnitedStates = "en_US@hw=US"
	case EnglishUnitedKingdom = "en_GB@hw=British"
	case EnglishJapan = "en_JP@hw=US"
	case EnglishIndia = "en_IN@hw=US"
	case SpanishSpain = "es_ES@hw=Spanish - ISO"
	case SpanishMexico = "es_MX@hw=Spanish - ISO"
	case EstonianEstonia = "et_EE@hw=Estonian"
	case Persian = "fa@hw=Persian"
	case FinnishFinland = "fi_FI@hw=Finnish"
	case FrenchBelgium = "fr_BE@hw=French"
	case FrenchFrance = "fr_FR@hw=French"
	case FrenchCanada = "fr_CA@hw=Canadian - CSA"
	case FrenchSwitzerland = "fr_CH@hw=Swiss French"
	case IrishIreland = "ga_IE@hw=British"
	case Gujarati = "gu@hw=Gujarati"
	case Hawaiian = "haw@hw=Hawaiian"
	case HebrewIsrael = "he_IL@hw=Hebrew"
	case Hindi = "hi@hw=Devanagari"
	case HindiTRANSLIT = "hi-Translit@hw=US"
	case HindiLatin = "hi_Latn@hw=US"
	case CroatianCroatia = "hr_HR@hw=Croatian"
	case HungarianHungary = "hu_HU@hw=Hungarian"
	case IndonesianIndonesia = "id_ID@hw=US"
	case IcelandicIceland = "is_IS@hw=Icelandic"
	case ItalianItaly = "it_IT@hw=Italian - Pro"
	case JapaneseJapanKANA = "ja_JP-Kana@hw=US"
	case JapaneseJapanROMAJI = "ja_JP-Romaji@hw=US"
	case Georgian = "ka@hw=US"
	case KoreanSouthKorea = "ko_KR@hw=2SetHangul"
	case LithuanianLithuania = "lt_LT@hw=Lithuanian"
	case LatvianLatvia = "lv_LV@hw=Latvian"
	case MacedonianMacedonia = "mk_MK@hw=Macedonian"
	case Marathi = "mr@hw=Devanagari-QWERTY"
	case MalayMalaysia = "ms_MY@hw=US"
	case NorwegianBokmålNorway = "nb_NO@hw=Norwegian"
	case DutchBelgium = "nl_BE@hw=Belgian"
	case DutchNetherlands = "nl_NL@hw=Dutch"
	case Punjabi = "pa@hw=Gurmukhi"
	case PolishPoland = "pl_PL@hw=Polish Pro"
	case PortugueseBrazil = "pt_BR@hw=Brazilian - Pro"
	case PortuguesePortugal = "pt_PT@hw=Portuguese"
	case RomanianRomania = "ro_RO@hw=Romanian"
	case RussianRussia = "ru_RU@hw=Russian"
	case SlovakSlovakia = "sk_SK@hw=Slovak"
	case SlovenianSlovenia = "sl_SI@hw=Slovenian"
	case SerbianCyrillic = "sr_Cyrl@hw=Serbian"
	case SerbianLatin = "sr_Latn@hw=Serbian-Latin"
	case SwedishSweden = "sv_SE@hw=Swedish - Pro"
	case Telugu = "te@hw=Telugu"
	case ThaiThailand = "th_TH@hw=Thai"
	case TagalogPhilippines = "tl_PH@hw=Spanish - ISO"
	case TurkishTurkey = "tr_TR@hw=Turkish-QWERTY-PC"
	case UkrainianUkraine = "uk_UA@hw=Ukrainian"
	case Urdu = "ur@hw=Urdu"
	case VietnameseVietnam = "vi_VN@hw=US"
	case ChineseSimplifiedPinyinRomanization = "zh_Hans-Pinyin@hw=US"
	case ChineseTraditionalZHUYIN = "zh_Hant-Zhuyin@hw=Zhuyin Bopomofo"
	case ChineseSimplifiedWUBIHUA = "zh_Hans-Wubihua@hw=US"
	case ChineseTaiwan = "zh_TW@hw=Zhuyin Bopomofo"
	case ChineseTraditionalCANGJIE = "zh_Hant-Cangjie@hw=CangjieKeyboard"
	case ChineseTraditionalWUBIHUA = "zh_Hant-Wubihua@hw=US"
	case ChineseTraditionalPinyinRomanization = "zh_Hant-Pinyin@hw=US"
	case ChineseTraditionalSUCHENG = "zh_Hant-Sucheng@hw=CangjieKeyboard"
	case ChineseChina = "zh_CN@hw=US"
}
