//
//  LocationAlert.swift
//  AutoMate
//
//  Created by Bartosz Janda on 14.02.2017.
//  Copyright © 2017 PGS Software. All rights reserved.
//

import XCTest

// =============================================================================
// == Not generated by ModelGenarator, but added manually to fullfill the test purposes.
// == We are albe to catch system alert from Location services.
// == Contacts alert cannot be handled by addUIInterruptionMonitor.
// == Possibility to catch other generated system service request models needs to be investigated further.
// ==
// TODO: This should be removed when:
// - Unit tests are provided to all system services
// - LocationAlert is being handled by ModelGenerator
// - HomeKitAlert is being handled by ModelGenerator
// - SystemAlertAllow and SystemAlertDeny is being extended by allow and
//   deny messages associated with LocationAlert and HomeKitAlert configuration.
public struct LocationAlert: SystemAlert, SystemAlertAllow, SystemAlertDeny {
    public static let messages = [
        //        "Allow „%@” to access your location while you use the app?"
        "to access your location while you use the app?"
    ]
    public var alert: XCUIElement

    public init?(element: XCUIElement) {
        guard let _ = element.any.elements(withLabelsMatchingExpressions: type(of: self).messages).first else {
            return nil
        }

        self.alert = element
    }
}
