// swiftlint:disable variable_name
/// Represents possible label values on alert buttons.
public class SystemAlertLabel {
	private init() {}

	/// Automatically generated property for localized variants of DontAllow.
	public static let DontAllow = [
		"No permetre",
		"Não permitir",
		"Tidak Boleh",
		"İzin Verme",
		"Tiltás",
		"허용 안 함",
		"Zakázat",
		"Tillåt inte",
		"Άρνηση",
		"Запретить",
		"Nepovoliť",
		"No permitir",
		"عدم السماح",
		"Ikke tillat",
		"Sta niet toe",
		"Refuser",
		"Non consentire",
		"Nie pozwalaj",
		"不允許",
		"Älä salli",
		"Nemoj dozvoliti",
		"Từ chối",
		"Tillad ikke",
		"不允许",
		"ไม่อนุญาต",
		"許可しない",
		"אל תאפשר",
		"Nu permiteți",
		"Não Permitir",
		"Jangan Benarkan",
		"Nein",
		"Заборонити",
		"अनुमति न दें",
		"Don’t Allow",
	]

	/// Automatically generated property for localized variants of Allow.
	public static let Allow = [
		"Engedélyezés",
		"允许",
		"Autoriser",
		"Tillat",
		"Permetre",
		"Salli",
		"Pozwalaj",
		"Sta toe",
		"अनुमति दें",
		"Dozvoli",
		"허용",
		"İzin Ver",
		"Να επιτρέπεται",
		"允許",
		"אפשר",
		"Permitir",
		"Povolit",
		"السماح",
		"Cho phép",
		"Izinkan",
		"Benarkan",
		"Tillåt",
		"อนุญาต",
		"Tillad",
		"許可",
		"Allow",
		"Permiteți",
		"Erlauben",
		"Povoliť",
		"Дозволити",
		"Разрешить",
		"Consenti",
	]

	/// Automatically generated property for localized variants of OK.
	public static let OK = [
		"ОК",
		"ΟΚ",
		"OKE",
		"موافق",
		"Tamam",
		"OK",
		"אישור",
		"ตกลง",
		"好",
		"확인",
		"ठीक",
	]

	/// Automatically generated property for localized variants of Cancel.
	public static let Cancel = [
		"Zrušit",
		"Batal",
		"Hủy",
		"Poništi",
		"キャンセル",
		"Cancelar",
		"Anulați",
		"Batalkan",
		"إلغاء",
		"取消",
		"रद्द करें",
		"Cancel·lar",
		"ยกเลิก",
		"Скасувати",
		"Annuler",
		"Abbrechen",
		"Annuleer",
		"Anuluj",
		"Vazgeç",
		"Отменить",
		"Annuller",
		"취소",
		"ביטול",
		"Avbryt",
		"Kumoa",
		"Zrušiť",
		"Ακύρωση",
		"Mégsem",
		"Annulla",
		"Cancel",
	]

}
