platform :ios, '9.3'
workspace '../AutoMate'

target 'AutoMateExample' do
  use_frameworks!

  # pod 'AutoMate-AppBuddy', git: 'https://github.com/PGSSoft/AutoMate-AppBuddy'
  pod 'AutoMate-AppBuddy', path: '../../pgs-automate-appbuddy-ios'

  # target 'AutoMateExampleUITests' do
  #   inherit! :search_paths
  # end

end
