platform :ios, '9.2'
workspace '../AutoMate'

target 'AutoMateExample' do
  use_frameworks!

  pod 'AutoMate-AppBuddy', git: 'https://github.com/PGSSoft/AutoMate-AppBuddy', :branch => 'develop'

  target 'AutoMateExampleUITests' do
    inherit! :search_paths

  end

end
